select_regions = [
    "EUW",
    "EUNE",
    "NA",
    "KR",
    "BR",
    "JP",
    "LAN",
    "LAS",
    "OCE",
    "PH",
    "RU",
    "SG",
    "TH",
    "TR",
    "TW",
    "VN",
    "ME",
]
api_regions_1 = {
    "EUW": "EUROPE",
    "EUNE": "EUROPE",
    "NA": "AMERICAS",
    "KR": "ASIA",
    "BR": "AMERICAS",
    "JP": "ASIA",
    "LAN": "AMERICAS",
    "LAS": "AMERICAS",
    "OCE": "ASIA",
    "PH": "ASIA",
    "RU": "EUROPE",
    "SG": "ASIA",
    "TH": "ASIA",
    "TR": "EUROPE",
    "TW": "ASIA",
    "VN": "ASIA",
    "ME": "EUROPE",
}
api_regions_2 = {
    "EUW": "EUW1",
    "EUNE": "EUN1",
    "NA": "NA1",
    "KR": "KR",
    "BR": "BR1",
    "JP": "JP1",
    "LAN": "LA1",
    "LAS": "LA2",
    "OCE": "OC1",
    "PH": "PH2",
    "RU": "RU",
    "SG": "SG2",
    "TH": "TH2",
    "TR": "TR1",
    "TW": "TW2",
    "VN": "VN2",
    "ME": "ME1",
}
api_region_2_to_select_region = {
    "EUW1": "EUW",
    "EUN1": "EUNE",
    "NA1": "NA",
    "KR": "KR",
    "BR1": "BR",
    "JP1": "JP",
    "LA1": "LAN",
    "LA2": "LAS",
    "OC1": "OCE",
    "PH2": "PH",
    "RU": "RU",
    "SG2": "SG",
    "TH2": "TH",
    "TR1": "TR",
    "TW2": "TW",
    "VN2": "VN",
    "ME1": "ME",
}
api_region_2_to_server_region = {
    "NA1": "AMERICAS",
    "BR1": "AMERICAS",
    "LA1": "AMERICAS",
    "LA2": "AMERICAS",
    "KR": "ASIA",
    "JP1": "ASIA",
    "EUW1": "EUROPE",
    "EUN1": "EUROPE",
    "RU": "EUROPE",
    "TR1": "EUROPE",
    "ME1": "EUROPE",
    "OC1": "SEA",
    "PH2": "SEA",
    "SG2": "SEA",
    "TH2": "SEA",
    "TW2": "SEA",
    "VN2": "SEA",
}

pro_regions = ["LCK", "LPL", "LEC", "LCS"]
teams_per_region = {
    "LCK": ["T1", "GENG", "DK", "DRX", "HLE", "KDF", "KT", "FOX", "BRO", "NS"],
    "LPL": [
        "AL",
        "BLG",
        "EDG",
        "FPX",
        "IG",
        "JDG",
        "LGD",
        "LNG",
        "NIP",
        "OMG",
        "RA",
        "RNG",
        "WE",
        "TES",
        "TT",
        "UP",
        "WBG",
    ],
    "LCS": ["TL", "C9", "FLY", "DIG", "100", "NRG", "SR", "IMT"],
    "LEC": ["FNC", "G2", "GX", "KC", "MAD", "RGE", "SK", "BDS", "TH", "VIT"],
}
