select_regions = [
    "EUW",
    "EUNE",
    "NA",
    "KR",
    "BR",
    "JP",
    "LAN",
    "LAS",
    "OCE",
    "PH",
    "RU",
    "SG",
    "TH",
    "TR",
    "TW",
    "VN",
]
api_regions_1 = {
    "EUW": "EUROPE",
    "EUNE": "EUROPE",
    "NA": "AMERICAS",
    "KR": "ASIA",
    "BR": "AMERICAS",
    "JP": "ASIA",
    "LAN": "AMERICAS",
    "LAS": "AMERICAS",
    "OCE": "ASIA",
    "PH": "ASIA",
    "RU": "EUROPE",
    "SG": "ASIA",
    "TH": "ASIA",
    "TR": "EUROPE",
    "TW": "ASIA",
    "VN": "ASIA",
}
api_regions_2 = {
    "EUW": "EUW1",
    "EUNE": "EUN1",
    "NA": "NA1",
    "KR": "KR",
    "BR": "BR1",
    "JP": "JP1",
    "LAN": "LA1",
    "LAS": "LA2",
    "OCE": "OC1",
    "PH": "PH2",
    "RU": "RU",
    "SG": "SG2",
    "TH": "TH2",
    "TR": "TR1",
    "TW": "TW2",
    "VN": "VN2",
}
api_regions_2_to_select_regions = {
    "EUW1": "EUW",
    "EUN1": "EUNE",
    "NA1": "NA",
    "KR": "KR",
    "BR1": "BR",
    "JP1": "JP",
    "LA1": "LAN",
    "LA2": "LAS",
    "OC1": "OCE",
    "PH2": "PH",
    "RU": "RU",
    "SG2": "SG",
    "TH2": "TH",
    "TR1": "TR",
    "TW2": "TW",
    "VN2": "VN",
}
